apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterParser
metadata:
  name: kubernetes-parser-traefik
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  regex:
      regex: ^.*\s+\[(?<timestamp>\d{2}\/[a-zA-Z]+\/\d{4}:\d{2}:\d{2}:\d{2}\s+\+\d+)\]\s+"(?<method>\w+)\s+(?<path>\S+)\s+(?<httpversion>[^"]+)"\s+(?<statuscode>\d+)\s+(?<bytes_content>\d+)\s+"-"\s+"-"\s+(?<number_of_requests_received_since_started>\d+)\s+"(?<ingress>[^"]+)"\s+"(?<url>[^"]+)"\s+(?<responsetime>\d+)ms$
      types: responsetime:integer
      timeKey: timestamp
      timeFormat: "%d/%b/%Y:%H:%M:%S %z"