apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterParser
metadata:
  name: kubernetes-parser
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  match: kube.var.log.traefik*
  regexp: