apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: kubernetes-filter
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  match: kube.var.log.containers.traef*
  filters:
    - parser:
        keyName: message
        parser: kubernetes-parser-traefik
    - modify:
        rules:
          - add:
              content: method path statuscode url ingress
